---
title: "Impact of parental resources on living standard potential"
subtitle: "Education, home ownership and housing wealth in post-socialist China"
author: "Langyi Tian, Columbia University"
date: "Aug 2019"
output: html_document
---      
###Setup
```{r setup}
#Set up default knitr chunk options
library("knitr")
knitr::opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.height = 9,
  fig.width = 15,
  fig.align = "center",
  cache = TRUE,
  cache.lazy = FALSE
)
options(htmltools.dir.version = FALSE)
```  

```{r theme-map}
#set up theme map
theme_simplemap <- function(base_size = 9,
                            base_family = "") {
  theme_bw(base_size = base_size, base_family = base_family) %+replace%
    theme(
      axis.line = element_blank(),
      axis.text = element_blank(),
      axis.ticks = element_blank(),
      axis.title = element_blank(),
      panel.background = element_blank(),
      panel.border = element_blank(),
      panel.grid = element_blank(),
      panel.spacing = unit(0, "lines"),
      plot.background = element_blank(),
      legend.position = "none"
    )
}
```

```{r packages, message = FALSE, warning = FALSE, echo=FALSE}
# Load packages.
packages <- c(
  "tidyr",
  "dplyr",
  "stringr",
  "purrr",
  "readstata13",
  "data.table",
  "knitr",
  "ggplot2",
  "bit64",
  "forcats",
  "tidyverse",
  "ordinal",
  "jtools",
  "quantreg",
  "TraMineR",
  "MASS"
)
packages <- lapply(
  packages,
  FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x)
      library(x, character.only = TRUE)
    }
  }
)
```

```{r set up working directory, echo=FALSE, warning=FALSE}
setwd("C:/Users/Administrator/Documents/GitHub/parental-wealth-impact")
Sys.setlocale("LC_TIME", "C")#Set to debug date transformation
Sys.setenv(TZ="Europe/Berlin")
select <- dplyr::select
```

```{r build plotting function for summary statistics, echo=FALSE, warning=FALSE}
#Build summary function
summary.var <- function(dta,
                        var,
                        title = NULL) {
  m <- ggplot(data = dta,
              aes(x = dta[[var]])) +
    ggtitle(title) +
    xlab(var) +
    ylab("num of ppl") +
    theme_classic()
  if (dta[[var]] %>% class == "numeric" |
      dta[[var]] %>% class == "integer") {
    m <- m + geom_histogram(binwidth = 5,
                            fill = "lightgreen") +
      labs(caption = "numeric") +
      theme(text = element_text(size = 20))
  }
  if (dta[[var]] %>% class == "character" |
      dta[[var]] %>% class == "factor" |
      dta[[var]] %>% class == "logical") {
    m <- m + geom_bar(fill = "lightskyblue") +
      labs(caption = "categorical") +
      theme(axis.text.x = element_text(angle = 30, hjust = 1)) +
      theme(text = element_text(size = 20))
  }
  return(m)
}
```

#CHARLS
###Parents
```{r impoart and subset 2015 demographics, echo=FALSE, warning=FALSE}
demographic_raw_2015 <-
  read.dta13("CHARLS2015/Demographic_Background.dta")
demographic_2015 <- demographic_raw_2015 %>% select(
  id = ID,
  hhid = householdID,
  communityID,
  role = ba000_w2_3,
  birthyear = ba004_w3_1,
  address0 = bb000_w3_2,
  otheraddress = bb001_w3,
  address1 = bb001_w3_2
)
```

```{r age and urban status, echo=FALSE, warning=FALSE}
#age
demographic_2015 <- demographic_2015 %>% mutate(id = id %>% as.character,
                                                age = 2015 - birthyear)
#Format transformation
for (var in c("address0",
              "otheraddress",
              "address1")) {
  demographic_2015[[var]] <- demographic_2015[[var]] %>% as.character()
  demographic_2015[[var]][is.na(demographic_2015[[var]]) == TRUE] <-
    "unkown"
}
#Update those who changed address since last survey
demographic_2015$address <- NA
for (i in 1:nrow(demographic_2015)) {
  if (demographic_2015$otheraddress[i] == 1) {
    demographic_2015$address[i] <- demographic_2015$address0[i]
  }
  if (demographic_2015$otheraddress[i] == 2) {
    demographic_2015$address[i] <- demographic_2015$address1[i]
  }
}
```
 
```{r hukou, echo=FALSE, warning=FALSE}
demographic_raw_2014 <-
  read.dta13("CHARLS2014/Demographic_Background.dta")
residence_2014 <-
  read.dta13("CHARLS2014/Residence.dta") %>% select(id = ID,
                                                    birthyear =
                                                      rbirthyear)
```


```{r, eval=FALSE}
hukou_2014 <- demographic_raw_2014 %>% select(
  id = ID,
  hhid = householdID,
  role = rgender,
  hukoutype,
  hk002_1_1_:hk002_1_6_,
  #change year
  hk004_1_:hk004_6_#new type
) %>% left_join(residence_2014, by = "id") %>%
  filter(role == "1 Male")
hukou_2014 <- hukou_2014 %>% mutate(id = id %>% as.character())
hukou_2014 <- hukou_2014 %>% filter(is.na(birthyear) == FALSE &
                                      is.na(hukoutype) == FALSE)
hukou_2014 <- hukou_2014 %>% select(
  id,
  hhid,
  birthyear,
  hukoutype,
  hk002_1_1_,
  hk004_1_,
  hk002_1_2_,
  hk004_2_,
  hk002_1_3_,
  hk004_3_,
  hk002_1_4_,
  hk004_4_,
  hk002_1_5_,
  hk004_5_,
  hk002_1_6_,
  hk004_6_
)
hukou <- NULL
for (i in 1:nrow(hukou_2014)) {
  adult_year <- hukou_2014$birthyear[i] + 18
  seq_raw <- cbind(
    c(
      adult_year,
      hukou_2014$hk002_1_1_[i],
      hukou_2014$hk002_1_2_[i],
      hukou_2014$hk002_1_3_[i],
      hukou_2014$hk002_1_4_[i],
      hukou_2014$hk002_1_5_[i],
      hukou_2014$hk002_1_6_[i],
      2015
    ),
    c(
      hukou_2014$hukoutype[i],
      hukou_2014$hk004_1_[i],
      hukou_2014$hk004_2_[i],
      hukou_2014$hk004_3_[i],
      hukou_2014$hk004_4_[i],
      hukou_2014$hk004_5_[i],
      hukou_2014$hk004_6_[i],
      "aha"
    )
  ) %>% as.data.frame() %>% na.omit()
  seq_full <- NULL
  seq_raw$num <- NA
  for (j in 1:(nrow(seq_raw) - 1)) {
    num <-
      (
        seq_raw$V1[j + 1] %>% as.character() %>% as.numeric() - seq_raw$V1[j] %>%
          as.character() %>% as.numeric()
      )
    if (num < 0) {
      num <- 10
    }
    seq <- rep(seq_raw$V2[j], num)
    seq_full <- c(seq_full, seq)
  }
  seq_full <- c(hukou_2014$id[i] %>% as.character(),
                hukou_2014$hhid[i] %>% as.character(),
                seq_full)
  length(seq_full) <- 80
  hukou <- rbind(hukou, seq_full)
}
hukou <- hukou %>% as.data.frame()
hukou[hukou == 3] <- 2
save(hukou, file = "output/hukou.RData")
```

```{r}
load("output/hukou.RData")
hukou_small <- hukou[, 1:30]
seq_hukou <- seqdef(hukou_small, 3:ncol(hukou_small))
dist_hukou <- seqdist(seq_hukou,
                      method = "OM",
                      with.missing = TRUE,
                      sm = "TRATE")
```

```{r, eval=FALSE}
kmeans_hukou_3 <- kmeans(
  dist_hukou,
  centers = 3,
  iter.max = 100,
  nstart = 3,
  algorithm = "Lloyd"
)
save(kmeans_hukou_3, file = "output/kmeans_hukou_3.RData")
```

```{r, eval=FALSE}
kmeans_hukou_3 <- fpc::clusterboot(
  dist_hukou,
  B = 3,
  bootmethod = "boot",
  multipleboot = TRUE,
  dissolution = 0.5,
  recover = 0.7,
  count = TRUE,
  showplots = FALSE,
  clustermethod = fpc::kmeansCBI,
  iter.max = 100,
  algorithm = "Lloyd",
  krange = 3
)
save(kmeans_hukou_3, file = "output/kmeans_hukou_3.RData")
```

```{r}
load("output/kmeans_hukou_3.RData")
```

```{r, eval=FALSE}
#Compute optimal number of clusters of K-means
bnclust_gap_plot1 <- factoextra::fviz_nbclust(
  dist_hukou,
  kmeans,
  k.max = 5,
  nboot = 10,
  method = "wss"
) +
  ggtitle("Within Sum of Square by Three Measures") +
  theme_classic()
bnclust_gap_plot2 <- factoextra::fviz_nbclust(
  dist_hukou,
  kmeans,
  k.max = 5,
  nboot = 10,
  method = "silhouette"
) +
  theme_classic()
bnclust_gap_plot3 <- factoextra::fviz_nbclust(
  dist_hukou,
  kmeans,
  k.max = 5,
  nboot = 10,
  method = "gap_stat"
) +
  labs(caption = "Source: MCA based on CFPS") +
  theme_classic()
gridExtra::grid.arrange(bnclust_gap_plot1,
                        bnclust_gap_plot2,
                        bnclust_gap_plot3,
                        ncol = 1)
```

```{r}
hukou_2014 <- cbind(id = hukou_small$V1 %>% as.character(),
                    hukou = kmeans_hukou_3$cluster %>% as.character()) %>% as.data.frame()
hukou_2014 <-
  hukou_2014 %>% mutate(hukou = hukou %>% factor(
    levels = c(2, 1, 3),
    labels = c("Ag",
               "Ag-NAg",
               "NAg")
  ))
```

```{r party, echo=TRUE, warning=FALSE}
#Select variable
party_2014 <- demographic_raw_2014 %>% select(id = ID,
                                              p022s1)
party_2014 <- party_2014 %>% mutate(id = id %>% as.character(),
                                    p022s1 = p022s1 %>% as.character)
party_2014$party <- 0
party_2014$party[party_2014$p022s1 == "1 The Respondent"] <- 1
party_2014$party <- party_2014$party %>% factor(levels = c(0, 1),
                                                labels = c("Not party member",
                                                           "Party member"))
party_2014 <- party_2014 %>% select(id,
                                    party)
```


```{r education, echo=FALSE, warning=FALSE}
education_raw_2014 <- read.dta13("CHARLS2014/Education_History.dta")
education_2014 <- education_raw_2014 %>% select(id = ID,
                                                e000s1:e000s12)
#Transform variables
for (i in names(education_2014)) {
  education_2014[[i]] <- education_2014[[i]] %>% as.character()
  education_2014[[i]][is.na(education_2014[[i]]) == TRUE] <-
    "missing"
}
#Recode education
education_2014$education <- education_2014$first_hukou
for (i in 1:nrow(education_2014)) {
  for (j in c(
    "e000s1",
    "e000s2",
    "e000s3",
    "e000s4",
    "e000s5",
    "e000s6",
    "e000s7",
    "e000s8",
    "e000s9",
    "e000s10",
    "e000s11",
    "e000s12"
  )) {
    if (education_2014[[j]][i] != "missing") {
      education_2014$education[i] <- education_2014[[j]][i]
    }
  }
}
education_2014$education[education_2014$education == "missing"] <- NA
```

```{r education ontinue, echo=TRUE, warning=FALSE}
education_2014$education_years <- NA
education_2014$education_years[education_2014$education == "1 Home School" |
                                 education_2014$education == "2 Kindergarten" |
                                 education_2014$education == "3 Preschool"] <-
  1
education_2014$education_years[education_2014$education == "12 None"] <-
  1
education_2014$education_years[education_2014$education == "4 Primary School"] <-
  6
education_2014$education_years[education_2014$education == "5 Middle School"] <-
  9
education_2014$education_years[education_2014$education == "6 High School"] <-
  12
education_2014$education_years[education_2014$education == "7 Vocational School"] <-
  11
education_2014$education_years[education_2014$education == "8 Three-year College"] <-
  15
education_2014$education_years[education_2014$education == "9 Four-year College"] <-
  16
education_2014$education_years[education_2014$education == "10 Master"] <-
  19
education_2014$education_years[education_2014$education == "11"] <- 22
```

```{r educatio, echo=TRUE, warning=FALSE}
education_2014$education[education_2014$education == "1 Home School" |
                           education_2014$education == "2 Kindergarten" |
                           education_2014$education == "3 Preschool" |
                           education_2014$education == "4 Primary School" |
                           education_2014$education == "12 None"] <- 1
education_2014$education[education_2014$education == "5 Middle School" |
                           education_2014$education == "6 High School"] <-
  2
education_2014$education[education_2014$education == "7 Vocational School" |
                           education_2014$education == "8 Three-year College"] <-
  3
education_2014$education[education_2014$education == "9 Four-year College" |
                           education_2014$education == "10 Master" |
                           education_2014$education == "11"] <- 4
education_2014$education <-
  education_2014$education %>% factor(
    levels = c(1:4),
    labels = c(
      "1 Below middle school",
      "2 Middle and High school",
      "3 Voc/3 yrs college",
      "4 Bachelor and above"
    )
  )
education_2014 <- education_2014 %>% select(id,
                                            education,
                                            education_years)
```

```{r occupation, echo=FALSE, warning=FALSE}
work_raw_2014 <- read.dta13("CHARLS2014/Work_History.dta")
```

```{r, eval=FALSE}
work_2014 <- work_raw_2014 %>% select(
  id = ID,
  hhid = householdID,
  f_2_1_0_:f_2_1_18_,
  #Start year for job 1-18
  f_2_5_0_:f_2_5_18_,
  #End year
  f_3_0_:f_3_18_,
  #Job category
  f104_0_:f104_18_,
  #Job category detailed
  f105_0_:f105_14_#detail firm
) %>% left_join(demographic_raw_2014 %>% select(id =
                                                  ID,
                                                role =
                                                  rgender),
                by = "id") %>% filter(role ==
                                        "1 Male")
work_2014 <- work_2014 %>% mutate(id = id %>% as.character())
work <- NULL
for (i in 1:nrow(work_2014)) {
  seq_full <- NULL
  for (j in 0:18) {
    start <- paste("f_2_1_", j, "_", sep = "")
    end <- paste("f_2_5_", j, "_", sep = "")
    cat1 <- paste("f_3_", j, "_", sep = "")
    cat2 <- paste("f104_", j, "_", sep = "")
    cat3 <- paste("f105_", j, "_", sep = "")
    if (is.na(work_2014[[start]][i]) == FALSE &
        is.na(work_2014[[cat1]][i]) == FALSE) {
      if (is.na(work_2014[[end]][i]) == FALSE) {
        end_year <- work_2014[[end]][i]
      } else{
        end_year <- 2014
      }
      duration <- end_year - work_2014[[start]][i]
      if (duration < 0) {
        duration <- duration * -1
        print(c(
          work_2014$id[i],
          "switch start/end year due to data mistake"
        ))
      }
      job <- work_2014[[cat1]][i] %>% as.character()
      if (job %in% c("2 Agricultural Employment",
                     "3 Non-agricultural Employment")) {
        job <- work_2014[[cat2]][i] %>% as.character()
        if (job %in% c("4 Firm")) {
          job <- work_2014[[cat3]][i] %>% as.character()
        }
      }
      job[job %in% c(
        "1 Own Agricultural Production and Business",
        "6 Farmer",
        "8 Rural Collective Economic Organization"
      )] <- "AG"
      job[job %in% c("6 Army",
                     "1 Government",
                     "2 Public Institution",
                     "1 State Controlled Firm")] <- "nAGin"
      job[job %in% c(
        "4 Non-agricultural self-employment",
        "5 Unpaid Household Business Help",
        "3 NGO",
        "5 Individual Firm",
        "7 Individual Household",
        "9 Other",
        "3 Private Controlled Firm",
        "4 Hongkong/Macao/Taiwan Controlled Firm",
        "5 Foreign Controlled Firm",
        "2 Collective Controlled Firm",
        "6 Other"
      )] <- "nAGout"
      seq <- rep(job, duration)
      seq_full <- c(seq_full, seq)
    }
  }
  seq_full <- c(work_2014$id[i] %>% as.character(),
                work_2014$hhid[i] %>% as.character(),
                seq_full)
  length(seq_full) <- 82
  work <- rbind(work, seq_full)
}
work <- work %>% as.data.frame()
save(work, file = "output/work.RData")
```

```{r, message=FALSE}
load("output/work.RData")
work_small <- work[, 1:33]
seq_work <- seqdef(work_small, 3:ncol(work_small))
dist_work <- seqdist(seq_work,
                     method = "OM",
                     with.missing = TRUE,
                     sm = "TRATE")
```

```{r, eval=FALSE}
kmeans_work_4 <- kmeans(
  dist_work,
  centers = 4,
  iter.max = 100,
  nstart = 4,
  algorithm = "Lloyd"
)
save(kmeans_work_4, file = "output/kmeans_work_4.RData")
```

```{r, eval=FALSE}
kmeans_work_4 <- fpc::clusterboot(
  dist_work,
  B = 1,
  bootmethod = "boot",
  multipleboot = TRUE,
  dissolution = 0.5,
  recover = 0.7,
  count = TRUE,
  showplots = FALSE,
  clustermethod = fpc::kmeansCBI,
  iter.max = 100,
  algorithm = "Lloyd",
  krange = 4
)
save(kmeans_work_4, file = "output/kmeans_work_4.RData")
```

```{r}
load("output/kmeans_work_4.RData")
```

```{r, eval=FALSE}
#Compute optimal number of clusters of K-means
bnclust_gap_plot1 <- factoextra::fviz_nbclust(
  dist_hukou,
  kmeans,
  k.max = 5,
  nboot = 10,
  method = "wss"
) +
  ggtitle("Within Sum of Square by Three Measures") +
  theme_classic()
bnclust_gap_plot2 <- factoextra::fviz_nbclust(
  dist_hukou,
  kmeans,
  k.max = 5,
  nboot = 10,
  method = "silhouette"
) +
  theme_classic()
bnclust_gap_plot3 <- factoextra::fviz_nbclust(
  dist_hukou,
  kmeans,
  k.max = 5,
  nboot = 10,
  method = "gap_stat"
) +
  labs(caption = "Source: MCA based on CFPS") +
  theme_classic()
gridExtra::grid.arrange(bnclust_gap_plot1,
                        bnclust_gap_plot2,
                        bnclust_gap_plot3,
                        ncol = 1)
```

```{r}
work_2014 <- cbind(id = work_small$V1 %>% as.character(),
                   jobcat = kmeans_work_4$cluster %>% as.character()) %>% as.data.frame()
work_2014 <-
  work_2014 %>% mutate(jobcat = jobcat %>% factor(
    levels = c(1, 4, 3, 2),
    labels = c("AG",
               "mixed",
               "nAGout",
               "nAGin")
  ))
```

```{r, eval=FALSE}
#Transform variables
start_years <- names(work_2014 %>% select(f_2_1_0_:f_2_1_18_))
end_years <- names(work_2014 %>% select(f_2_5_0_:f_2_5_18_))
job_cat <- names(work_2014 %>% select(f_3_0_:f_3_18_))
for (i in c(start_years,
            end_years)) {
  work_2014[[i]] <- work_2014[[i]] %>% as.numeric()
  work_2014[[i]][is.na(work_2014[[i]]) == TRUE] <- 0
}
for (i in job_cat) {
  work_2014[[i]] <- work_2014[[i]] %>% as.character()
}
#Choose the job with longest tenure
work_2014$num <- NA
for (i in 1:nrow(work_2014)) {
  work_2014$num[i] <- 1
  duration <- 0
  duration_top <-
    work_2014[[end_years[2]]][i] - work_2014[[start_years[2]]][i]
  for (j in 3:(length(start_years))) {
    if (work_2014[[end_years[j]]][i] != 0) {
      duration <-
        work_2014[[end_years[j]]][i] - work_2014[[start_years[j]]][i]
      if (duration > duration_top) {
        work_2014$num[i] <- (j - 1)
        duration_top <- duration
      }
    }
  }
}
#Return job category
for (i in 1:nrow(work_2014)) {
  work_2014$jobcat[i] <-
    work_2014[[paste("f_3_", work_2014$num[i], "_", sep = "")]][i]
}
work_2014 <- work_2014 %>% select(id,
                                  jobcat)
```

```{r ind income, echo=FALSE, warning=FALSE}
ind_income_raw_2015 <- read.dta13("CHARLS2015/Individual_Income.dta")
ind_income_2015 <- ind_income_raw_2015 %>% select(
  id = ID,
  #Asset
  hhid = householdID,
  hc001,
  #cash on hand
  hc002_bracket_max:hc002_bracket_min,
  hc005,
  #Bank deposit,
  hc006_bracket_max,
  hc006_bracket_min,
  hc008,
  #gov bond,
  hc009_bracket_max,
  hc009_bracket_min,
  hc013,
  #stock
  hc014_bracket_max,
  hc014_bracket_min,
  hc018,
  #funds
  hc019_bracket_max,
  hc019_bracket_min,
  hc028,
  #HPF
  hc029_bracket_max,
  hc029_bracket_min,
  hc031,
  #work unit funding
  hc032_bracket_max,
  hc032_bracket_min,
  hc034,
  #unpaid salary
  hc035_bracket_max,
  hc035_bracket_min,
  #Debt
  hc040_w3,
  #debt collectable
  hc041_w3_bracket_max,
  hc041_w3_bracket_min,
  hd001,
  #unpaid private debt
  hd002_bracket_max,
  hd002_bracket_min,
  hc037,
  #payable private debt,
  hc038_w3_bracket_max,
  hc038_w3_bracket_min,
  hd003,
  #credit card payable
  hd004_bracket_max,
  hd004_bracket_min,
  hd004_w3,
  #other debt payable
  hd004_w3_1_bracket_max,
  hd004_w3_1_bracket_min
)
```

```{r, echo=FALSE, warning=FALSE}
ind_income_2015[is.na(ind_income_2015)] <- 0
ind_income_2015[ind_income_2015 < 0] <- 0
ind_income_2015 <-
  ind_income_2015 %>% mutate(
    asset_fin = (hc001 * 2 + hc002_bracket_max + hc002_bracket_min) / 2 +
      (hc005 * 2 + hc006_bracket_max + hc006_bracket_min) /
      2 +
      (hc008 * 2 + hc009_bracket_max + hc009_bracket_min) /
      2 +
      (hc013 * 2 + hc014_bracket_max + hc014_bracket_min) /
      2 +
      (hc018 * 2 + hc019_bracket_max + hc019_bracket_min) /
      2 +
      (hc028 * 2 + hc029_bracket_max + hc029_bracket_min) /
      2 +
      (hc031 * 2 + hc032_bracket_max + hc032_bracket_min) /
      2 +
      (hc034 * 2 + hc035_bracket_max + hc035_bracket_min) /
      2 +
      (hc040_w3 * 2 + hc041_w3_bracket_max + hc041_w3_bracket_min) /
      2,
    debt_fin =
      (hd001 * 2 + hd002_bracket_max + hd002_bracket_min) /
      2 +
      (hc037 * 2 + hc038_w3_bracket_max + hc038_w3_bracket_min) /
      2 +
      (hd003 * 2 + hd004_bracket_max + hd004_bracket_min) /
      2 +
      (hd004_w3 * 2 + hd004_w3_1_bracket_max + hd004_w3_1_bracket_min) /
      2
  )
ind_income_2015 <-
  ind_income_2015 %>% mutate(net_fin = asset_fin - debt_fin)
ind_income_2015 <- ind_income_2015 %>% select(id,
                                              hhid,
                                              net_fin)
hh_fin_networth <-
  ind_income_2015 %>% group_by(hhid) %>% summarise(asset_fin = sum(net_fin, na.rm =
                                                                     TRUE))
```


```{r current home value, echo=FALSE, warning=FALSE}
hh_income_raw_2015 <- read.dta13("CHARLS2015/Household_Income.dta")
hh_income_2015 <- hh_income_raw_2015 %>% select(
  hhid = householdID,
  homeownership = ha007,
  rent = ha005,
  homevalueunit = ha011,
  homevalue = ha011_1,
  homevalue2 = ha011_2,
  bracketlow = ha012_bracket_min,
  brackethigh = ha012_bracket_max,
  samehouse = ha000_w2_1,
  ha065_1_1_:ha065_1_19_,
  #durables
  ha066_1_1_:ha066_1_6_,
  #fixed asset for agriculture
  ha067,
  #fixed asset for business
  ha068_1,
  #other fixed asset
)
hh_income_2015$homevalue[hh_income_2015$homevalue < 0] <- NA
```

```{r}
hh_asset_2015 <- hh_income_raw_2015 %>% select(
  hhid = householdID,
  ha057_1_:ha057_4_,
  #lands
  ha065_1_1_:ha065_1_19_,
  #durables
  ha066_1_1_:ha066_1_6_,
  #fixed asset for agriculture
  ha067,
  #fixed asset for business
  ha068_1#other fixed asset
)
hh_asset_2015[is.na(hh_asset_2015)] <- 0
hh_asset_2015[hh_asset_2015 < 0] <- 0
hh_asset_2015 <- hh_asset_2015 %>% mutate(
  asset_land = (ha057_1_ +
                  ha057_1_ +
                  ha057_2_ +
                  ha057_3_ +
                  ha057_4_) * 20,
  asset_durable_fixed = ha065_1_1_ +
    ha065_1_2_ +
    ha065_1_3_ +
    ha065_1_4_ +
    ha065_1_5_ +
    ha065_1_6_ +
    ha065_1_7_ +
    ha065_1_8_ +
    ha065_1_9_ +
    ha065_1_10_ +
    ha065_1_11_ +
    ha065_1_12_ +
    ha065_1_13_ +
    ha065_1_14_ +
    ha065_1_15_ +
    ha065_1_16_ +
    ha065_1_17_ +
    ha065_1_18_ +
    ha065_1_19_ +
    ha066_1_1_ +
    ha066_1_2_ +
    ha066_1_3_ +
    ha066_1_4_ +
    ha066_1_5_ +
    ha066_1_6_ +
    ha067 +
    ha068_1
)
hh_asset_2015 <-
  hh_asset_2015 %>% mutate(asset = asset_land + asset_durable_fixed)
hh_asset_2015 <- hh_asset_2015 %>% select(hhid,
                                          asset_land,
                                          asset_durable_fixed,
                                          asset)
```

```{r networth}
networth_2015 <- full_join(hh_asset_2015, hh_fin_networth, by = "hhid")
networth_2015 <- networth_2015 %>% mutate(hhid = hhid %>% as.character(),
                                          net_worth = asset + asset_fin)
```
 
```{r home characteristics 2013, echo=FALSE, warning=FALSE}
hh_income_raw_2013 <- read.dta13("CHARLS2013/Household_Income.dta")
hh_income_2013 <- hh_income_raw_2013 %>% select(
  hhid = householdID,
  buildarea = ha001_w2,
  obtainway = ha016,
  obtainyear = ha017,
  obtaincost = ha018
)
hh_income_2015 <- left_join(hh_income_2015,
                            hh_income_2013,
                            by = "hhid")
```

```{r home characteristics, echo=FALSE, warning=FALSE}
hh_house_raw_2015 <-
  read.dta13("CHARLS2015/Housing_Characteristics.dta")
hh_house_2015 <- hh_house_raw_2015 %>% select(
  hhid = householdID,
  buildyear = i005,
  buildyear_range = i005_1,
  bedrooms = i012_1
)
house_2015 <- full_join(hh_income_2015,
                        hh_house_2015,
                        by = "hhid")
```

```{r create home value, echo=FALSE, warning=FALSE}
for (i in 1:nrow(house_2015)) {
  if (is.na(house_2015$samehouse[i]) == FALSE &
      house_2015$samehouse[i] == "2 No") {
    house_2015$buildarea[i] <- NA
    house_2015$obtainway[i] <- NA
    house_2015$obtainyear[i] <- NA
    house_2015$obtaincost[i] <- NA
  }
  if (is.na(house_2015$homevalue[i]) == FALSE &
      house_2015$homevalue[i] >= 1000) {
    house_2015$homevalue[i] <- house_2015$homevalue[i] / 10000
  }
  if (is.na(house_2015$homevalue2[i]) == FALSE &
      house_2015$homevalue2[i] > 1000) {
    house_2015$homevalue[i] <- house_2015$homevalue[i] / 1000
  }
  if (is.na(house_2015$homevalue[i]) == TRUE &
      house_2015$homevalueunit[i] == "2 Unit Price (1000 Yuan/M2)" &
      is.na(house_2015$buildarea[i]) == FALSE &
      is.na(house_2015$homevalue2[i]) == FALSE) {
    if (house_2015$homevalue2[i] >= 500) {
      house_2015$homevalue2[i] <- house_2015$homevalue2[i] / 1000
    }
    house_2015$homevalue[i] <-
      house_2015$buildarea[i] * house_2015$homevalue2[i] / 10
  }
  if (is.na(house_2015$homevalue[i]) == TRUE &
      is.na(house_2015$bracketlow[i]) == FALSE &
      is.na(house_2015$brackethigh[i]) == FALSE) {
    house_2015$homevalue[i] <-
      (house_2015$bracketlow[i] + house_2015$brackethigh[i]) / (2 * 10000)
  } else if (is.na(house_2015$homevalue[i]) == TRUE &
             is.na(house_2015$bracketlow[i]) == FALSE) {
    house_2015$homevalue[i] <- house_2015$bracketlow[i] / 10000
  } else if (is.na(house_2015$homevalue[i]) == TRUE &
             is.na(house_2015$brackethigh[i]) == FALSE) {
    house_2015$homevalue[i] <- house_2015$brackethigh[i] / 10000
  }
}
house_2015 <- house_2015 %>% select(hhid,
                                    homeownership,
                                    homevalue,
                                    obtainway,
                                    obtainyear,
                                    obtaincost)

for (i in 1:nrow(house_2015)) {
  if (is.na(house_2015$obtaincost[i]) == FALSE &
      house_2015$obtaincost[i] >= 500) {
    house_2015$obtaincost[i] <- house_2015$obtaincost[i] / 10000
  }
}
house_2015$obtainway <- house_2015$obtainway %>% as.character()
house_2015$obtainway[house_2015$obtainway == "1 Market"] <- "Market"
house_2015$obtainway[house_2015$obtainway == "2 Working Unit of Household Member"] <-
  "Working unit"
house_2015$obtainway[house_2015$obtainway == "6 Self-built"] <-
  "Self-built"
house_2015$obtainway[house_2015$obtainway == "8 Compensation for Old Home"] <-
  "Compensation for Old Home"
house_2015$obtainway[house_2015$obtainway %in% c(
  "3 Child Non-household Member",
  "4 Parents Non-household Member",
  "5 Other Relatives",
  "7 Inherited or Given",
  "9 Other"
)] <- "Other"
house_2015$homevalue[house_2015$homeownership == "3 None of Household Member"] <-
  0
house_2015 <- house_2015 %>% mutate(hhid = hhid %>% as.character()
)
```

```{r Merge all 2014, echo=FALSE, warning=FALSE}
ind_2014 <- full_join(hukou_2014, party_2014, by = "id")
ind_2014 <- full_join(ind_2014, education_2014, by = "id")
ind_2014 <- full_join(ind_2014, work_2014, by = "id")
```

```{r Merge 2014 and 2015, echo=FALSE, warning=FALSE}
ind_2015 <- demographic_2015 %>% select(-address0,-otheraddress,-address1,-birthyear,)
dta_ind <- full_join(ind_2014, ind_2015, by = "id")
dta_hh <- full_join(dta_ind, house_2015, by = "hhid")
dta_hh <- full_join(dta_hh, networth_2015, by = "hhid")
dta_hh <-
  dta_hh %>% mutate(net_worth_real = (net_worth + homevalue * 10000) / 10000)
```

###Child
```{r}
psu_raw <- read.dta13("CHARLS2013/PSU.dta",
                      fromEncoding = "GB2312",
                      convert.factors = FALSE)
psu_raw$tier <- NA
psu_raw$tier[psu_raw$city %in% c(
  "上海市",
  "北京",
  "深圳市",
  "广州市",
  "重庆市",
  "天津",
  "苏州市",
  "成都市",
  "武汉市",
  "杭州市",
  "南京市",
  "西安市",
  "长沙市",
  "沈阳市",
  "青岛市",
  "郑州市",
  "大连市",
  "东莞市",
  "宁波市"
)] <- "tier1"
psu_raw$tier[psu_raw$city %in% c(
  "厦门市",
  "福州市",
  "无锡市",
  "合肥市",
  "昆明市",
  "哈尔滨市",
  "哈尔滨",
  "济南市",
  "佛山市",
  "长春市",
  "温州市",
  "石家庄市",
  "南宁市",
  "常州市",
  "泉州市",
  "南昌市",
  "贵阳市",
  "太原市",
  "烟台市",
  "嘉兴市",
  "南通市",
  "金华市",
  "珠海市",
  "惠州市",
  "徐州市",
  "海口市",
  "乌鲁木齐市",
  "绍兴市",
  "中山市",
  "台州市",
  "兰州市"
)] <- "tier2"
psu_raw$tier[psu_raw$city %in% c(
  "潍坊市",
  "保定市",
  "镇江市",
  "扬州市",
  "桂林市",
  "唐山市",
  "三亚市",
  "湖州市",
  "呼和浩特市",
  "廊坊市",
  "洛阳市",
  "威海市",
  "盐城市",
  "临沂市",
  "江门市",
  "汕头市",
  "泰州市",
  "漳州市",
  "邯郸市",
  "济宁市",
  "芜湖市",
  "淄博市",
  "银川市",
  "柳州市",
  "绵阳市",
  "湛江市",
  "鞍山市",
  "赣州市",
  "大庆市",
  "宜昌市",
  "包头市",
  "咸阳市",
  "秦皇岛市",
  "株洲市",
  "莆田市",
  "吉林市",
  "淮安市",
  "肇庆市",
  "宁德市",
  "衡阳市",
  "南平市",
  "连云港市",
  "丹东市",
  "丽江市",
  "揭阳市",
  "延边朝鲜族自治州",
  "舟山市",
  "九江市",
  "龙岩市",
  "沧州市",
  "抚顺市",
  "襄阳市",
  "上饶市",
  "营口市",
  "三明市",
  "蚌埠市",
  "丽水市",
  "岳阳市",
  "清远市",
  "荆州市",
  "泰安市",
  "衢州市",
  "盘锦市",
  "东营市",
  "南阳市",
  "马鞍山市",
  "南充市",
  "西宁市",
  "孝感市",
  "齐齐哈尔市"
)] <- "tier3"
psu_raw$tier[is.na(psu_raw$tier) == TRUE] <- "tier4"
psu <- psu_raw %>% select(cid = communityID,
                          tier)
```

```{r import child data, echo=FALSE, warning=FALSE}
child_raw_2015 <- read.dta13("CHARLS2015/Child.dta")
#Child data
child_2015 <- child_raw_2015 %>% select(
  id = ID,
  hhid = householdID,
  cid = communityID,
  childid = childID,
  gender = gender,
  age = age,
  independence = cb053,
  distance = cb053_2,
  education = cb052_w3,
  hukou = cb055,
  marriage = cb063,
  party = cb063_w3_2,
  income = cb069,
  home = cb071_w3,
  homevalue = cb072_w3,
  urban = cb054
) %>% left_join(psu, by = "cid")
```

```{r child gender}
child_2015$gender <-
  child_2015$gender %>% as.numeric() %>% factor(levels = c(2, 1),
                                                labels = c("Female",
                                                           "Male"))
```

```{r Marriage status, echo=TRUE, warning=FALSE}
child_2015$marriage <- child_2015$marriage %>% as.character()
child_2015$marriage[child_2015$marriage == "1 Married With Spouse At Present" |
                      child_2015$marriage == "2 Married But Not Living With Spouse Temporarily" |
                      child_2015$marriage == "3 Separated" |
                      child_2015$marriage == "4 Divorced" |
                      child_2015$marriage == "5 Widowed"] <- 2
child_2015$marriage[child_2015$marriage == "6 Never Married" |
                      child_2015$marriage == "7 Cohabitated"] <- 1
child_2015$marriage <- child_2015$marriage %>% factor(levels = c(1, 2),
                                                      labels = c("Not married",
                                                                 "Married"))
```

```{r}
child_2015$party <-
  child_2015$party %>% as.numeric %>% factor(levels = c(2, 1),
                                             labels = c("Not Party member",
                                                        "Party member"))
```

```{r Hukou, echo=TRUE, warning=FALSE}
child_2015$hukou <- child_2015$hukou %>% as.character()
child_2015$hukou[child_2015$hukou == "3 Unified Residency Hukou"] <-
  "2 Non-Agricultural Hukou"
child_2015$hukou[child_2015$hukou == "4 Does Not Have Hukou"] <- NA
```

```{r Urban status, echo=TRUE, warning=FALSE}
address <- demographic_2015 %>% select(hhid,
                                       role,
                                       address)
child_2015$address_parent <- NA
for (i in 1:nrow(child_2015)) {
  hhidi <- child_2015$hhid[i]
  addresses <- address %>% filter(hhid == hhidi)
  if (addresses$address[addresses$role == "1 male"] %>% length > 0) {
    child_2015$address_parent[i] <-
      addresses$address[addresses$role == "1 male"][1]
  } else{
    if (addresses$address[addresses$role == "2 female"] %>% length > 0)
      child_2015$address_parent[i] <-
        addresses$address[addresses$role == "2 female"][1]
  }
}
```

```{r urban status continue, echo=TRUE, warning=FALSE}
child_2015$urban <- child_2015$urban %>% as.character()
for (i in 1:nrow(child_2015)) {
  if (child_2015$independence[i] %in% c(
    "1 This Household, And Economicly Dependent",
    "2 This Household, But Economicly Independent",
    "3 The Same Or Adjacent Dwelling/Courtyard With You"
  )) {
    child_2015$urban[i] <- child_2015$address_parent[i]
  }
  if (child_2015$independence[i] %in% c(
    "4 Another Household In Your Permanent Address's Village/Neighorhood",
    "5 Another Village/Neighborhood In Your Permanent Address's County/City/District"
  ) &
  is.na(child_2015$urban[i]) == TRUE) {
    child_2015$urban[i] <- child_2015$address_parent[i]
  }
}
```

```{r}
child_2015$urban[child_2015$urban %in% c("1 Main City Zone")] <- 3
child_2015$urban[child_2015$urban %in% c(
  "2 Combination Zone Between Urban and Rural Areas",
  "2 Combination Zone Between Urban And Rural Areas"
)] <- 2
child_2015$urban[child_2015$urban %in% c("3 The Town Center",
                                         "4 ZhenXiang Area",
                                         "5 Special Area",
                                         "6 Township Central",
                                         "7 Village")] <- 1
child_2015$urban[child_2015$urban %in% c("unkown")] <- NA
child_2015$urban <- child_2015$urban %>% factor(
  levels = c(1:3),
  labels = c(
    "1 other",
    "2 Combination Zone Between Urban And Rural Areas",
    "3 Main City Zone"
  )
)
```

```{r Education, echo=TRUE, warning=FALSE}
child_2015$education <- child_2015$education %>% as.character()
child_2015$education_years <- NA
child_2015$education_years[child_2015$education == "1 No formal education illiterate"] <-
  0
child_2015$education_years[child_2015$education == "2 Did not finish primary school but capable of reading or writing" |
                             child_2015$education == "3 Sishu/home school"] <-
  3
child_2015$education_years[child_2015$education == "4 Elementary school"] <-
  6
child_2015$education_years[child_2015$education == "5 Middle school"] <-
  9
child_2015$education_years[child_2015$education == "6 High school"] <-
  12
child_2015$education_years[child_2015$education == "7 Vocational school"] <-
  11
child_2015$education_years[child_2015$education == "8 Two-/Three-Year College / Associate degree"] <-
  14
child_2015$education_years[child_2015$education == "9 Four-Year College / Bachelors degree"] <-
  16
child_2015$education_years[child_2015$education == "10 Post-graduate, Masters degree"] <-
  19
child_2015$education_years[child_2015$education == "11 Post-graduate, doctoral degree/Ph.D."] <-
  22
```

```{r, echo=TRUE, warning=FALSE}
child_2015$education[child_2015$education == "1 No formal education illiterate" |
                       child_2015$education == "2 Did not finish primary school but capable of reading or writing" |
                       child_2015$education == "3 Sishu/home school" |
                       child_2015$education == "4 Elementary school" |
                       child_2015$education == "5 Middle school"] <- 1
child_2015$education[child_2015$education == "6 High school"] <- 2
child_2015$education[child_2015$education == "7 Vocational school" |
                       child_2015$education == "8 Two-/Three-Year College / Associate degree"] <-
  3
child_2015$education[child_2015$education == "9 Four-Year College / Bachelors degree" |
                       child_2015$education == "10 Post-graduate, Masters degree" |
                       child_2015$education == "11 Post-graduate, doctoral degree/Ph.D."] <-
  4
child_2015$education <- child_2015$education %>% factor(
  levels = c(1:4),
  labels = c(
    "1 Middle school and below",
    "2 Middle and high school",
    "3 Vocational school/some college",
    "4 Bachelor and above"
  )
)
```


```{r Income, echo=TRUE, warning=FALSE}
child_2015$income <-
  child_2015$income %>% as.character() %>% str_extract("^[:digit:]+ ") %>% as.numeric() %>% factor(
    levels = (1:12),
    labels = c(
      "0",
      "1000",
      "2500",
      "7500",
      "15000",
      "25000",
      "40000",
      "75000",
      "125000",
      "175000",
      "250000",
      "500000"
    )
  )%>%as.character()%>%as.numeric()
```

```{r Occupation, echo=FALSE, warning=FALSE}
child_raw_2013 <- read.dta13("CHARLS2013/Child.dta")
child_2013 <- child_raw_2013 %>% select(id = ID,
                                        childid = childID,
                                        jobcat = cb071)
child_2013$jobcat <- child_2013$jobcat %>% as.character()
child_2013$jobcat[child_2013$jobcat == "5 Agricultural, Forestry, Husbandry and Fishery Producer"] <-
  1
child_2013$jobcat[child_2013$jobcat == "6 Production and Transportation worker"] <-
  2
child_2013$jobcat[child_2013$jobcat == "4 Commerical and Service worker"] <-
  3
child_2013$jobcat[child_2013$jobcat == "3 Clerk"] <- 4
child_2013$jobcat[child_2013$jobcat == "2 Professional and Technician"] <-
  5
child_2013$jobcat[child_2013$jobcat == "1 Manager"] <- 6
child_2013$jobcat <- child_2013$jobcat %>% factor(
  levels = c(1:6),
  labels = c(
    "1 Peasants",
    "2 Industrial workers",
    "3 Employees of services",
    "4 Clerical personnel",
    "5 Professionals and Technicians",
    "6 State, social and enterprise managers"
  )
)
child_2015 <- right_join(child_2013,
                         child_2015,
                         by = c("id", "childid"))
```

```{r Home value, echo=FALSE, warning=FALSE}
child_2015$homevalue[child_2015$home == "2 No"] <- 0
child_2015$homevalue[child_2015$homevalue < 0] <- NA
child_2015$homevalue[child_2015$homevalue > 1000] <- 1000
```

```{r, echo=FALSE, warning=FALSE}
transfer_raw_2015 <- read.dta13("CHARLS2015/Family_Transfer.dta")
transfer_2015 <- transfer_raw_2015 %>% select(
  hhid = householdID,
  ce029_1_1_:ce029_1_16_,
  #money support
  ce069_w2_1_1_:ce069_w2_1_15_,
  ce070_w2_1_1_:ce070_w2_1_9_
)#buy marriage house
transfer_2015$ce069_w2_1_16_ <- "2"
```

```{r, echo=FALSE, warning=FALSE}
transfer_raw_2013 <- read.dta13("CHARLS2013/Family_Transfer.dta")
transfer_2013 <- transfer_raw_2013 %>% select(hhid = householdID,
                                              ce031_1_1_:ce031_1_11_)#money support
```

```{r, echo=FALSE, warning=FALSE}
child_2015$gift <- NA
child_2015$transfer <- NA
child_2015$marriagehome <- NA
child_2015$marriagehomevalue <- NA
for (i in 1:nrow(child_2015)) {
  household <- child_2015$hhid[i]
  if (household %in% transfer_2015$hhid) {
    record <- transfer_2015 %>% filter(hhid == household)
    #marriage home
    child_2015$marriagehome[i] <- record[[paste("ce069_w2_1_",
                                                child_2015$childid[i],
                                                "_",
                                                sep = "")]]
    if (child_2015$childid[i] <= 9) {
      child_2015$marriagehomevalue[i] <- record[[paste("ce070_w2_1_",
                                                       child_2015$childid[i],
                                                       "_",
                                                       sep = "")]]
    }
    #Gift transfer
    child_2015$gift[i] <- record[[paste("ce029_1_",
                                        child_2015$childid[i],
                                        "_",
                                        sep = "")]]
    if (household %in% transfer_2013$hhid & child_2015$childid[i] <= 11) {
      record_2013 <- transfer_2013 %>% filter(hhid == household)
      if (is.null(record_2013[[paste("ce031_1_",
                                     child_2015$childid[i],
                                     sep = "")]]) == FALSE) {
        gift_2013[is.na(gift_2013) == TRUE] <- 0
        child_2015$gift[i] <- child_2015$gift[i] + gift_2013
      }
    }
  }
}
child_2015$gift[child_2015$gift < 0] <- 0
child_2015$gift[is.na(child_2015$gift) == TRUE] <- 0
child_2015$marriagehome[is.na(child_2015$marriagehome) == TRUE] <-
  "No marriage home"
child_2015$marriagehome[child_2015$marriagehome == 2] <-
  "No marriage home"
child_2015$marriagehome[child_2015$marriagehome == 1] <-
  "Parent buy marriage home"
for (i in 1:nrow(child_2015)) {
  if (is.na(child_2015$marriagehomevalue[i]) == FALSE &
      child_2015$marriagehomevalue[i] >= 1000) {
    child_2015$marriagehomevalue[i] <-
      child_2015$marriagehomevalue[i] / 1000
  }
  if (is.na(child_2015$marriagehomevalue[i]) == TRUE &
      child_2015$marriagehome[i] == "Parent buy marriage home") {
    child_2015$marriagehomevalue[i] <-
      child_2015$marriagehomevalue %>% median(na.rm = TRUE)
  }
}
child_2015$marriagehomevalue[is.na(child_2015$marriagehomevalue)] <- 0
```

```{r Final processing, echo=FALSE, warning=FALSE}
child <- child_2015 %>% select(-distance,-address_parent)
#Add prefix of "child_" to all vars
names(child)[!names(child) %in% c("childid",
                                  "hhid",
                                  "cid")] <-
  names(child)[!names(child) %in% c("childid",
                                    "hhid",
                                    "cid")] %>% str_c("child", sep = "_")
```

```{r Only keep householder in parent family, echo=FALSE, warning=FALSE}
unique_hhids <- dta_hh$hhid %>% unique()
householder <- NULL
for (i in unique_hhids) {
  dta <- dta_hh %>% filter(hhid == i)
  dta <- dta[order(dta$role, decreasing = FALSE), ]
  record <- dta[1, ]
  householder <- householder %>% rbind(record)
}
```

### Merge parent and child data
```{r Merge parent and child data, echo=TRUE, warning=FALSE}
merged_charls <- inner_join(child, householder, by = c("hhid"))
```

```{r, echo=FALSE, warning=FALSE}
merged_charls$onlychild <- NA
for (i in 1:nrow(merged_charls)) {
  dta <-
    merged_charls %>% filter(merged_charls$hhid == merged_charls$hhid[i])
  if (nrow(dta) == 1) {
    merged_charls$onlychild[i] <- "only child"
  }
  if (nrow(dta) > 1 & merged_charls$childid[i] == 1) {
    merged_charls$onlychild[i] <- "first child"
  }
  if (nrow(dta) > 1 & merged_charls$childid[i] > 1) {
    merged_charls$onlychild[i] <- "later child"
  }
}
save(merged_charls, file = "output/merged_charls.RData")
save(seq_hukou, file = "output/seq_hukou.RData")
save(seq_work, file = "output/seq_work.RData")
```
